/**
 * NarraPic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface AuthResponse { 
    access_token?: string;
    refresh_token?: string;
    expires_in?: number;
    token_type?: string;
    user?: User;
}

