/**
 * NarraPic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Channel = {
    Sms: 'sms',
    Whatsapp: 'whatsapp'
} as const;
export type Channel = typeof Channel[keyof typeof Channel];

