/**
 * NarraPic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContentResponse { 
    id?: string;
    description?: string;
    shortCaption?: string;
    platform?: string;
    altText?: string;
    hashtags?: Array<string>;
}

