/**
 * NarraPic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Channel } from './channel';


export interface Credentials { 
    phone?: string;
    email?: string;
    password?: string;
    channel?: Channel;
}
export namespace Credentials {
}


