/**
 * NarraPic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Platform } from './platform';
import { Style } from './style';


export interface Generate { 
    image_url?: string;
    prompt?: string;
    platform?: Platform;
    style?: Style;
}
export namespace Generate {
}


