/**
 * NarraPic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Platform = {
    LtzInsta: 'ltz_insta',
    LtzTiktok: 'ltz_tiktok'
} as const;
export type Platform = typeof Platform[keyof typeof Platform];

