/**
 * NarraPic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Style = {
    LtzInspEng: 'ltz_insp_eng',
    LtzPro: 'ltz_pro',
    LtzCasual: 'ltz_casual',
    LtzPromo: 'ltz_promo'
} as const;
export type Style = typeof Style[keyof typeof Style];

