/**
 * NarraPic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: string;
    email?: string;
    name?: string;
    createdAt?: string;
    updatedAt?: string;
}

